### ISSUE TITLE
[Issue]: Mod Loading Errror (Possibly Agricraft)

### ISSUE THREAD

**Issue by SauceyJoBBQ** [The-Nexus-Project/Limitless-5#134]
### What happened?

Exported folders: _config, defaultconfigs, saves_ from version 1.13 and updated the pack from 1.13 to 1.15 (hf). I then used the exported folders to override the current folders in the pack. I then tried to load the modpack and got a mod loading error.

### Pack Version

Version: 1.15 (hf)

### To Reproduce

1.  Export 1.13 folders (for backup)
     - config
     - defaultconfigs
     - saves
2. Update from 1.13 to 1.15 (hf)
3. Replace the 1.15 files with the 1.13 exported files
4. Attempt to load modpack

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
https://github.com/SauceyJoBBQ/Minecraft-Crash-Report/blob/4e5e0f762c6536aa7e1f5e763bb54bf7f82dbf6b/crash-2022-07-15_19.58.19-fml.txt
```

**Comment by PhantomEnderium** [comment]
My assumption is that while your save SHOULD be fine, the configs have been changed from the past few updates and therefore aren't compatible

**Comment by TopPercentageRattata** [comment]
This is due to new Create version not being compatible with Agricraft's Create compatability. Deleting old configs and copying over new configs should fix it like someone else said. 
New config setup has enableCreateCompat set to false in line 268 of config/agricraft/config-client.toml and also deletes create folders in config/aricraft/json/default and config/agricraft/json/server_localhost

**Comment by SauceyJoBBQ** [comment]
> My assumption is that while your save SHOULD be fine, the configs have been changed from the past few updates and therefore aren't compatible

Okay thank you, I'll try that
