### ISSUE TITLE
[Issue]: Bundle Dupe 

### ISSUE THREAD

**Issue by GeneTakovic7316** [The-Nexus-Project/Limitless-5#189]
### What happened?

I was messing around with backpacks and accidentally found a dupe glitch which allows you to dupe any item using bundles.

### Pack Version

Version: 2.21.1

### To Reproduce

1. Get any backpack from sophisticated backpacks and any stack upgrade for it
2. Get two or more bundles depending on stack upgrade tier.
3. Put the bundles into the backpack, they should stack, next grab the item you want to dupe and right click it on the bundles, the one item should go into the bundles
4. Take bundles out and right click on the air to empty them, the items duped
5. Profit

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

To fix it disable bundle stacking in backpacks.

**Comment by Gbergz** [comment]
Try reporting to Sophisticated Backpacks. See what they say.

**Comment by SlackerCat1** [comment]
This bug was reported on to the sophisticated backpack crew awhile ago. And mostly is a quark problem. Their solution is adding it to the `nonStackableItems` config file for sophisticated backpacks. I'll put a link to their github report on it as it has a little more information:

https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/396

**Comment by Gbergz** [comment]
added bundle to that config.
